CREATE TABLE routes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  destination VARCHAR(150) NOT NULL,
  amount_per_trip DECIMAL(10,2) NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
